"use strict";

/** 手写 ambient 事件 — 按时代/圈层分类，避免模板复读 */
module.exports = {
  /* ---------- 全时代通用（都市日常，可叠加任意年代） ---------- */
  universal: [
    { id: "U001", category: "居住", layerId: "L1", text: "合租房热水器坏了，房东说「凑活用」。你洗了一周冷水。", d: { health: -4, money: -1 }, weight: 7 },
    { id: "U002", category: "居住", layerId: "L2", text: "物业通知电梯检修三天。你爬了十七层，到公司时衬衫湿透。", d: { health: -3, rep: -1 }, weight: 6 },
    { id: "U003", category: "金钱", layerId: "L2", text: "工资到账短信和花呗还款提醒几乎同时弹出。", d: { money: -1, health: -2 }, weight: 8 },
    { id: "U004", category: "健康", layerId: "L2", text: "体检报告建议「复查」。预约电话打了三次才接通。", d: { health: -3, money: -1 }, weight: 7 },
    { id: "U005", category: "职场", layerId: "L2", text: "周会延长四十分钟，主题只有一个：「降本增效」。", d: { rep: -1, health: -3 }, weight: 8 },
    { id: "U006", category: "人情", layerId: "L2", text: "同事结婚，礼金标准在群里「通气」过。你按中间档转过去。", d: { money: -2, social: 3 }, weight: 7 },
    { id: "U007", category: "教育", layerId: "L3", text: "夜校招生简章写「周末两天，改变一生」。学费等于你半月伙食。", d: { money: -1, edu: 4 }, weight: 6 },
    { id: "U008", category: "机会", layerId: "L3", text: "前同事创业，朋友圈发招聘：「不看学历，看扛压。」", d: { rep: 2, social: 2 }, weight: 5 },
    { id: "U009", category: "风险", layerId: "L5", text: "短信：「您的账户异常，请点击链接。」你删了，类似的一月还有七条。", d: { health: -1 }, weight: 4 },
    { id: "U010", category: "健康", layerId: "L1", text: "外卖迟到四十分钟，骑手电话说「电梯坏了」。你给了差评又撤了。", d: { health: -2, social: -1 }, weight: 6 },
    { id: "U011", category: "职场", layerId: "L3", text: "绩效面谈，主管用「潜力」这个词。你知道下一句通常是「但」。", d: { rep: -2, health: -2 }, weight: 7 },
    { id: "U012", category: "金钱", layerId: "L3", text: "基金绿了一周。App 推送：「长期主义。」", d: { money: -1, health: -2 }, weight: 6 },
    { id: "U013", category: "居住", layerId: "L3", text: "邻居装修，电钻从八点响到六点。物业说「已备案」。", d: { health: -4 }, weight: 7 },
    { id: "U014", category: "人情", layerId: "L3", text: "老家亲戚问「能不能帮孩子安排实习」。你解释了半小时城市规则。", d: { social: -2, rep: 1 }, weight: 6 },
    { id: "U015", category: "机会", layerId: "L4", text: "行业峰会邀请函，门票四位数。公司报销名额只有一个。", d: { rep: 3, social: 2 }, weight: 5 },
    { id: "U016", category: "职场", layerId: "L4", text: "董事会旁听席。你第一次听见「现金流」被说得像天气。", d: { rep: 4, edu: 2 }, weight: 4 },
    { id: "U017", category: "金钱", layerId: "L4", text: "私人银行经理约茶，推荐一款「稳健型」产品。条款厚得像字典。", d: { money: -2, rep: 2 }, weight: 4 },
    { id: "U018", category: "健康", layerId: "L4", text: "私家体检中心，护士说「您这年龄该加项了」。加项比基础贵三倍。", d: { money: -2, health: 4 }, weight: 5 },
    { id: "U019", category: "居住", layerId: "L4", text: "物业费上调通知，理由写「提升服务品质」。", d: { money: -1, rep: 1 }, weight: 5 },
    { id: "U020", category: "教育", layerId: "L2", text: "孩子学校家委会征集「自愿」赞助。你看见别的家长已经接龙。", d: { money: -1, social: 2 }, weight: 6, minAge: 30 },
    { id: "U021", category: "职场", layerId: "L2", text: "工位换成开放式。降噪耳机成为办公室硬通货。", d: { health: -3, rep: 1 }, weight: 7 },
    { id: "U022", category: "金钱", layerId: "L1", text: "菜市场涨价，摊主说「进货也贵」。你数了数零钱，够买三天。", d: { money: -1, health: -1 }, weight: 8 },
    { id: "U023", category: "人情", layerId: "L1", text: "老乡群有人发拼多多砍一刀。你帮了，没人帮你的。", d: { social: -1 }, weight: 5 },
    { id: "U024", category: "机会", layerId: "L2", text: "内部竞聘，岗位比申请人少一半。HR 说「流程公开透明」。", d: { rep: 2, health: -3 }, weight: 6 },
    { id: "U025", category: "风险", layerId: "L3", text: "兼职刷单广告：「日结三百。」你举报了，类似弹窗还在。", d: { rep: 1 }, weight: 4 },
    { id: "U026", category: "健康", layerId: "L3", text: "颈椎理疗，医保不报销。技师说「你这行普遍这样」。", d: { money: -1, health: 5 }, weight: 6 },
    { id: "U027", category: "职场", layerId: "L2", text: "考勤改为人脸识别。你迟到那天的照片被自动发给了主管。", d: { rep: -3 }, weight: 7 },
    { id: "U028", category: "金钱", layerId: "L2", text: "信用卡积分兑换，换到的东西不如直接买便宜。", d: { money: -1 }, weight: 5 },
    { id: "U029", category: "居住", layerId: "L2", text: "租约到期，房东涨租「市场价」。你算了算搬家成本，签了。", d: { money: -2, health: -2 }, weight: 8 },
    { id: "U030", category: "教育", layerId: "L3", text: "职称评审材料装订费、照片费、复印费——加起来像一门小课。", d: { money: -1, rep: 3 }, weight: 6, minAge: 26 },
    { id: "U031", category: "职场", text: "公司换打卡系统，人脸录入三次失败。IT 说「光线问题」。", d: { rep: -1, health: -2 }, weight: 6 },
    { id: "U032", category: "金钱", text: "水电燃气「一户一表」改造，分摊费争议在群里吵了一周。", d: { money: -1, health: -2 }, weight: 6 },
    { id: "U033", category: "健康", text: "通勤单程九十分钟。你在地铁上睡着，坐过站两次。", d: { health: -3, rep: -1 }, weight: 7 }
  ],

  /* ---------- 分时代事件（贴合真实历史语境） ---------- */
  byEra: {
    E1: [
      { id: "E1_01", category: "职场", text: "单位发了一袋米、一桶油。你拎上公交车，全车都闻得到。", d: { social: 3, money: 1 }, weight: 8 },
      { id: "E1_02", category: "职场", text: "分房名单贴在大院公告栏。没有你，有同事。你们互相没看眼睛。", d: { rep: -3, social: -2 }, weight: 7 },
      { id: "E1_03", category: "机会", text: "街道有人私下问：「有没有门路换全国粮票？」你摇头。", d: { rep: 1 }, weight: 5 },
      { id: "E1_04", category: "金钱", text: "工资四十三块五，精确到分。你把它存进铁皮饼干盒。", d: { money: 1, health: 1 }, weight: 8 },
      { id: "E1_05", category: "人情", text: "师傅退休，徒弟凑钱买了块表。你出两块，工资里的一顿。", d: { money: -1, social: 4 }, weight: 7 },
      { id: "E1_06", category: "教育", text: "夜大招生，单位名额两个。车间里五个人「争取」。", d: { rep: 2, social: -1 }, weight: 6 },
      { id: "E1_07", category: "居住", text: "筒子楼公用水龙头结冰。你端盆排队，聊的是谁家孩子考上大学。", d: { social: 2, health: -2 }, weight: 7 },
      { id: "E1_08", category: "职场", text: "「下海」这个词开始在广播里出现。老同志说：「看看就行。」", d: { edu: 2, rep: -1 }, weight: 6 },
      { id: "E1_09", category: "健康", text: "厂医院体检，医生说「血压偏高，少操心」。", d: { health: -2 }, weight: 6 },
      { id: "E1_10", category: "机会", text: "深圳来的亲戚穿的确良，说那边「能挣钱」。你记住了，没动。", d: { edu: 3 }, weight: 5 },
      { id: "E1_11", category: "金钱", text: "孩子学费单位报销。你第一次觉得「单位」像另一个家。", d: { money: 1, social: 2 }, weight: 6, minAge: 28 },
      { id: "E1_12", category: "职场", text: "班组评先进，名额一个。大家投票，你投给了真正干活的人。", d: { rep: 2, social: 1 }, weight: 6 },
      { id: "E1_13", category: "人情", text: "同事孩子满月，送二十块红包。回礼是一包糖。", d: { money: -1, social: 2 }, weight: 5 },
      { id: "E1_14", category: "风险", text: "有人倒腾电子表赚差价，被保卫科谈话。你旁听，没发言。", d: { rep: 1, health: -1 }, weight: 4 },
      { id: "E1_15", category: "居住", text: "煤炉冒烟，邻居敲门说呛。你换了个风向，继续煮。", d: { health: -2, social: -1 }, weight: 5 },
      { id: "E1_16", category: "教育", text: "成人高考复习班，课本是影印本。灯灭了就着蜡烛看。", d: { edu: 5, health: -3 }, weight: 6 },
      { id: "E1_17", category: "职场", text: "厂长作报告三小时，关键词：「稳定」「大局」。", d: { health: -2, rep: 1 }, weight: 7 },
      { id: "E1_18", category: "金钱", text: "国库券发行，同事排队买。你钱不够，借了点。", d: { money: 2, rep: -1 }, weight: 5 },
      { id: "E1_19", category: "机会", text: "单位办三产，招「有关系」的管仓库。你没去试。", d: { social: -1, rep: 1 }, weight: 4 },
      { id: "E1_20", category: "健康", text: "食堂菜里偶尔有虫。你挑出来，继续吃——别的桌也这样。", d: { health: -1 }, weight: 5 }
    ],
    E2: [
      { id: "E2_01", category: "机会", text: "辞职信模板在复印店公开卖。五块钱一份，含「个人原因」。", d: { rep: 2, edu: 2 }, weight: 8 },
      { id: "E2_02", category: "金钱", text: "摆地摊卖磁带，一晚挣的比工资多。你心动，没敢辞。", d: { money: 1, health: -2 }, weight: 7 },
      { id: "E2_03", category: "职场", text: "单位「停薪留职」政策出台。走廊里悄悄算谁先去海南。", d: { social: 2, rep: -1 }, weight: 7 },
      { id: "E2_04", category: "风险", text: "「原始股」传单塞进信箱。邻居买了，你看见他在楼道哭。", d: { rep: 2, health: -1 }, weight: 5 },
      { id: "E2_05", category: "机会", text: "百货公司柜台转租，月租三千。你算了算，要卖多少条皮带。", d: { edu: 3, money: -1 }, weight: 6 },
      { id: "E2_06", category: "人情", text: "跑业务的表哥回来，请吃饭。桌上讲「回扣」像讲天气。", d: { social: 3, rep: -2 }, weight: 6 },
      { id: "E2_07", category: "金钱", text: "万元户上了报纸。你数了数存折，四位数，差一位。", d: { rep: 1, health: -1 }, weight: 7 },
      { id: "E2_08", category: "职场", text: "外资厂来招人，英语要「能读说明书」。你报了夜校。", d: { edu: 4, money: -1 }, weight: 6 },
      { id: "E2_09", category: "居住", text: "城乡结合部自建房出租，没合同。押一付三，口头约定。", d: { money: -2, health: -1 }, weight: 7 },
      { id: "E2_10", category: "教育", text: "会计证培训班广告：「三个月上岗」。教室在居民楼里。", d: { edu: 5, money: -1 }, weight: 6 },
      { id: "E2_11", category: "机会", text: "股票认购证排队，有人雇你代排，给五十块。", d: { money: 2, health: -3 }, weight: 5 },
      { id: "E2_12", category: "风险", text: "传销亲戚来电：「过来玩，包吃住。」你挂了，家里吵了一架。", d: { social: -4, health: -2 }, weight: 4 },
      { id: "E2_13", category: "职场", text: "国企合并，科室撤销。名单上有你，调岗工资降半档。", d: { rep: -2, money: -1 }, weight: 7 },
      { id: "E2_14", category: "金钱", text: "民间借贷写「月息两分」。你当担保人签了个字。", d: { money: 1, rep: -4 }, weight: 4 },
      { id: "E2_15", category: "人情", text: "生意伙伴请客，茅台瓶口有针眼。你知道，仍碰了杯。", d: { social: 2, health: -2 }, weight: 5 },
      { id: "E2_16", category: "机会", text: "货运站招跟车，管饭不管命。你干了两个月，攒下第一笔胆。", d: { money: 2, health: -4 }, weight: 6 },
      { id: "E2_17", category: "居住", text: "城中村握手楼，电线像蜘蛛网。房东说：「住惯就好。」", d: { health: -3, money: -1 }, weight: 7 },
      { id: "E2_18", category: "教育", text: "自考文凭到手，人才市场仍问「全日制吗」。", d: { edu: 4, rep: -1 }, weight: 6 },
      { id: "E2_19", category: "职场", text: "个体执照办下来，公章刻了，账还是糊涂的。", d: { rep: 2, money: -1 }, weight: 6 },
      { id: "E2_20", category: "健康", text: "路边诊所打点滴，没处方。好得快，你不知药名。", d: { money: -1, health: 4 }, weight: 5 }
    ],
    E3: [
      { id: "E3_01", category: "金钱", text: "房改算工龄，每差一年多交几千。你恨自己毕业晚。", d: { money: -2, rep: -1 }, weight: 8 },
      { id: "E3_02", category: "机会", text: "拆迁测量队进小区，红漆写「拆」。邻居开始比面积。", d: { money: 3, social: -2 }, weight: 6 },
      { id: "E3_03", category: "居住", text: "按揭合同签字按手印，按完手还在抖。三十年，利息够再买半套。", d: { money: -2, rep: 3 }, weight: 8, minAge: 25 },
      { id: "E3_04", category: "职场", text: "公司搬进了写字楼，门禁刷卡。保安比厂长凶。", d: { rep: 1, social: -1 }, weight: 6 },
      { id: "E3_05", category: "金钱", text: "房价周报贴中介玻璃上。你每周路过，像看体育比分。", d: { edu: 2, health: -2 }, weight: 7 },
      { id: "E3_06", category: "机会", text: "「零首付」广告，小字写「风险自担」。你算了算，没签。", d: { rep: 2 }, weight: 5 },
      { id: "E3_07", category: "人情", text: "买房托了熟人，说能便宜两个点。最后发现大家都「托了」。", d: { social: -2, money: -1 }, weight: 6 },
      { id: "E3_08", category: "教育", text: "学区房政策一出，亲戚问你能不能「挂名」。", d: { social: -1, rep: 2 }, weight: 5, minAge: 28 },
      { id: "E3_09", category: "风险", text: "非法集资暴雷，单位有人跳楼。食堂安静了一周。", d: { health: -4, rep: 1 }, weight: 4 },
      { id: "E3_10", category: "职场", text: "地产公司招聘，底薪低提成高。「年薪百万不是梦」。", d: { rep: 2, money: -1 }, weight: 6 },
      { id: "E3_11", category: "居住", text: "装修队拖工期，你说一句，工头说「材料没到」。", d: { money: -2, health: -3 }, weight: 7 },
      { id: "E3_12", category: "金钱", text: "第二套房限购，你拿结婚证和纳税证明跑三次窗口。", d: { rep: 1, health: -2 }, weight: 5, minAge: 32 },
      { id: "E3_13", category: "机会", text: "小城市土地拍卖，朋友问要不要凑份子。你怕，没进。", d: { social: -1, rep: 1 }, weight: 5 },
      { id: "E3_14", category: "健康", text: "搬新家甲醛味，孩子咳嗽。你买绿萝，一屋二十盆。", d: { money: -1, health: -3 }, weight: 6, minAge: 28 },
      { id: "E3_15", category: "职场", text: "公司配车取消，改发交通补贴。补贴不够 parking。", d: { money: -1, rep: -1 }, weight: 6 },
      { id: "E3_16", category: "人情", text: "乔迁酒摆十桌，礼金记在本上。人情债开始按平米算。", d: { money: -2, social: 4 }, weight: 6 },
      { id: "E3_17", category: "教育", text: "MBA 招生，学费够付小城市首付。同学名单里有你的客户。", d: { edu: 5, money: -3 }, weight: 4, minAge: 30 },
      { id: "E3_18", category: "金钱", text: "物业维修基金公示，数字看不懂，签字栏要签。", d: { rep: -1 }, weight: 5 },
      { id: "E3_19", category: "机会", text: "商铺返租广告：「十年回本」。律师朋友说「看合同第八页」。", d: { edu: 3, money: -1 }, weight: 5 },
      { id: "E3_20", category: "风险", text: "首付一部分来自信用卡套现。你还了，利息记了三年。", d: { money: -2, health: -3 }, weight: 4 }
    ],
    E4: [
      { id: "E4_01", category: "职场", text: "公司发电脑，预装正版 Windows。IT 说「别装乱七八糟的」。", d: { rep: 2, edu: 2 }, weight: 7 },
      { id: "E4_02", category: "机会", text: "博客时代，你写技术帖，收到第一封猎头邮件。", d: { rep: 4, social: 2 }, weight: 7 },
      { id: "E4_03", category: "金钱", text: "网吧包夜五块，你写方案写到天亮。老板送了一瓶可乐。", d: { money: -1, health: -4, rep: 2 }, weight: 6 },
      { id: "E4_04", category: "教育", text: "远程 MBA 广告：「不出国门拿学位」。你分辨不了真假。", d: { edu: 2, money: -1 }, weight: 5 },
      { id: "E4_05", category: "职场", text: "996 写在招聘页底部，小字。「弹性工作制」。", d: { health: -4, money: 1 }, weight: 8 },
      { id: "E4_06", category: "机会", text: "同事辞职去「互联网大厂」，工牌照片发论坛，点击量破万。", d: { rep: 2, social: 1 }, weight: 6 },
      { id: "E4_07", category: "金钱", text: "支付宝红包，第一次线上付款，你紧张得像丢现金。", d: { edu: 2 }, weight: 6 },
      { id: "E4_08", category: "风险", text: "P2P 理财，年化 12%。同事说「有担保」。", d: { money: 2, rep: -3 }, weight: 5 },
      { id: "E4_09", category: "人情", text: "QQ 群结婚通知，红包 fifty。你不知对方是谁，还是发了。", d: { money: -1, social: 1 }, weight: 5 },
      { id: "E4_10", category: "居住", text: "青年公寓，四人间，网速按人头分。你半夜改 bug，室友骂。", d: { health: -3, social: -2 }, weight: 7 },
      { id: "E4_11", category: "职场", text: "期权协议，行权价像天书。HR 说「上市就自由」。", d: { edu: 3, rep: 1 }, weight: 6 },
      { id: "E4_12", category: "健康", text: "久坐腰椎，买了人体工学椅。公司不让换，你自费。", d: { money: -1, health: 4 }, weight: 6 },
      { id: "E4_13", category: "机会", text: "创业孵化器，免费咖啡和无限梦想。隔壁团队已换第三波人。", d: { rep: 2, social: 2 }, weight: 6 },
      { id: "E4_14", category: "教育", text: "培训班承诺「包就业」，合同写「推荐就业」。一字之差。", d: { edu: 3, money: -2 }, weight: 5 },
      { id: "E4_15", category: "金钱", text: "股票账户开户，大厅大妈比你还懂 K 线。", d: { money: 1, edu: 2 }, weight: 6 },
      { id: "E4_16", category: "职场", text: "外企裁员，N+1 计算器在论坛流传。你默默存了链接。", d: { rep: -1, edu: 3 }, weight: 6 },
      { id: "E4_17", category: "机会", text: "团购网站挖人，工资翻倍。你去了，发现补贴战已开始。", d: { money: 2, health: -4 }, weight: 5 },
      { id: "E4_18", category: "风险", text: "游戏装备被盗，报警回执有了，装备没有。", d: { money: -1, health: -2 }, weight: 4 },
      { id: "E4_19", category: "人情", text: "前同事借 LinkedIn 内推，你改了七版简历。", d: { rep: 3, social: 2 }, weight: 6 },
      { id: "E4_20", category: "健康", text: "外卖吃多了，体检甘油三酯箭头向上。医生推了 Diet 单。", d: { health: -3, money: -1 }, weight: 7 }
    ],
    E5: [
      { id: "E5_01", category: "职场", text: "打车软件报销，财务要求「行程单与会议一致」。", d: { rep: -1, health: -2 }, weight: 7 },
      { id: "E5_02", category: "机会", text: "O2O 补贴大战，一块钱吃满汉全席。你知道这不会久。", d: { money: 1, edu: 2 }, weight: 7 },
      { id: "E5_03", category: "金钱", text: "余额宝收益每天几毛，你仍每天打开看。", d: { money: 1 }, weight: 6 },
      { id: "E5_04", category: "居住", text: "长租公寓，年付优惠。六个月后运营商跑路。", d: { money: -3, health: -3 }, weight: 6 },
      { id: "E5_05", category: "职场", text: "钉钉打卡，外勤要拍照。你在客户厕所补自拍。", d: { rep: 1, health: -2 }, weight: 7 },
      { id: "E5_06", category: "机会", text: "自媒体账号十万粉，广告报价单像工资条。", d: { money: 2, rep: 3 }, weight: 5 },
      { id: "E5_07", category: "风险", text: "校园贷广告贴到写字楼厕所。同事笑，你删了截图。", d: { rep: 1 }, weight: 4 },
      { id: "E5_08", category: "教育", text: "在线课程「知识付费」，买完发现是百度能搜到的。", d: { money: -1, edu: 1 }, weight: 6 },
      { id: "E5_09", category: "人情", text: "朋友圈集赞换礼品，你麻烦二十个人。礼品是 USB 线。", d: { social: -1 }, weight: 5 },
      { id: "E5_10", category: "健康", text: "共享单车堆成山，你扛车过马路，像健身。", d: { health: -2 }, weight: 5 },
      { id: "E5_11", category: "金钱", text: "信用卡分期买手机，月供等于以前一整月话费。", d: { money: -1, rep: 1 }, weight: 7 },
      { id: "E5_12", category: "职场", text: "公司发期权，上市前你签保密。朋友问，你只能「还行」。", d: { rep: 2, social: -1 }, weight: 6 },
      { id: "E5_13", category: "机会", text: "直播带货试水，一晚卖出三件。其中一件是你妈买的。", d: { money: 1, social: 2 }, weight: 5 },
      { id: "E5_14", category: "风险", text: "虚拟货币朋友群，有人 overnight 财务自由。你围观，没进。", d: { rep: 1, edu: 2 }, weight: 4 },
      { id: "E5_15", category: "居住", text: "合租室友是网约车司机，凌晨四点引擎声叫醒你。", d: { health: -4, social: -1 }, weight: 7 },
      { id: "E5_16", category: "职场", text: "裁员赔偿计算器小程序流传。你打开又关掉。", d: { health: -2, edu: 2 }, weight: 7 },
      { id: "E5_17", category: "教育", text: "少儿编程班，学费一万二。孩子喜欢，你刷卡。", d: { money: -2, social: 2 }, weight: 5, minAge: 30 },
      { id: "E5_18", category: "金钱", text: "花呗还最低，利息像第二份房租。", d: { money: -1, health: -2 }, weight: 8 },
      { id: "E5_19", category: "机会", text: "加入「斜杠青年」社群，名片上头衔比简历长。", d: { rep: 2, social: 3 }, weight: 5 },
      { id: "E5_20", category: "健康", text: "外卖骑手撞了护栏，新闻一闪而过。你取消订单，自己煮面。", d: { health: 2, money: -1 }, weight: 6 }
    ],
    E6: [
      { id: "E6_01", category: "职场", text: "「毕业」优化，赔偿方案三档。你选了中间，签字手稳。", d: { money: 2, rep: -2, health: -3 }, weight: 8 },
      { id: "E6_02", category: "机会", text: "考公报名人数破纪录。你报名，竞争比三百比一。", d: { edu: 4, health: -3 }, weight: 7 },
      { id: "E6_03", category: "金钱", text: "理财爆雷，维权群五百人。律师费众筹，进度缓慢。", d: { money: -2, health: -3 }, weight: 6 },
      { id: "E6_04", category: "居住", text: "二手房挂牌半年，中介建议「再降五十万」。", d: { money: -2, rep: -1 }, weight: 7, minAge: 30 },
      { id: "E6_05", category: "职场", text: "远程办公常态化，开会从床到床。边界消失。", d: { health: -3, rep: 1 }, weight: 7 },
      { id: "E6_06", category: "教育", text: "考研二战，自习室月卡比 gym 贵。你成了常驻。", d: { edu: 5, money: -1, health: -3 }, weight: 6, minAge: 22, maxAge: 28 },
      { id: "E6_07", category: "机会", text: "社区团购团长，邻居喊你「团长」。利润薄，面子厚。", d: { social: 3, money: 1 }, weight: 5 },
      { id: "E6_08", category: "风险", text: "电信诈骗，对方报出你身份证号。你挂电话，手抖。", d: { health: -4 }, weight: 5 },
      { id: "E6_09", category: "人情", text: "随礼标准又涨了。你翻旧账本，发现十年涨五倍。", d: { money: -2, social: 1 }, weight: 7 },
      { id: "E6_10", category: "健康", text: "核酸排队两小时，太阳晒。你想起以前不用这样。", d: { health: -2 }, weight: 6 },
      { id: "E6_11", category: "金钱", text: "消费降级，购物车清空，只留必需品。你并不快乐。", d: { money: 1, health: -2 }, weight: 7 },
      { id: "E6_12", category: "职场", text: "35 岁门槛写在招聘页「优先」。你 34，倒计时。", d: { rep: -3, health: -4 }, weight: 8, minAge: 32, maxAge: 38 },
      { id: "E6_13", category: "机会", text: "副业摆摊卖柠檬茶，城管来前邻居喊「来了」。", d: { money: 1, health: -2 }, weight: 6 },
      { id: "E6_14", category: "教育", text: "职业技能补贴，申请表格比考试难。", d: { edu: 3, health: -2 }, weight: 5 },
      { id: "E6_15", category: "居住", text: "房贷转 LPR，跑银行两次。省下的钱够两顿外卖。", d: { money: 1, health: -1 }, weight: 6, minAge: 28 },
      { id: "E6_16", category: "职场", text: "公司团建强制，周末爬山。你腿抖，照片仍要笑。", d: { health: -3, social: 1 }, weight: 6 },
      { id: "E6_17", category: "金钱", text: "信用卡降额，通知短信一行。你查了流水，没问题。", d: { rep: -1, health: -2 }, weight: 6 },
      { id: "E6_18", category: "机会", text: "旧同事做跨境电商，朋友圈晒仓库。你问教程，要九千八。", d: { edu: 2, money: -1 }, weight: 5 },
      { id: "E6_19", category: "健康", text: "心理咨询纳入讨论，你预约，排队三周。", d: { money: -1, health: 5 }, weight: 6 },
      { id: "E6_20", category: "风险", text: "担保签字帮朋友，朋友失联。律师信到了。", d: { money: -3, rep: -4 }, weight: 4 }
    ],
    E7: [
      { id: "E7_01", category: "职场", text: "AI 写周报工具内测，主管说「人人都要会用」。", d: { edu: 4, rep: 1 }, weight: 8 },
      { id: "E7_02", category: "机会", text: "灵活用工平台，接单「按件计酬」。时薪算下来不如以前。", d: { money: 1, health: -3 }, weight: 7 },
      { id: "E7_03", category: "金钱", text: "存款利率一降再降，老人排队买国债。你排在后面。", d: { money: -1, edu: 2 }, weight: 7 },
      { id: "E7_04", category: "居住", text: "保交楼新闻里出现你买的那家开发商。你查进度，更新很慢。", d: { health: -4, money: -2 }, weight: 6, minAge: 28 },
      { id: "E7_05", category: "职场", text: "办公室讨论「降本增效」第三波。咖啡机取消了。", d: { rep: -1, health: -2 }, weight: 8 },
      { id: "E7_06", category: "机会", text: "短视频账号尝试，第三条爆了，第四条没人看。", d: { rep: 2, social: 2 }, weight: 6 },
      { id: "E7_07", category: "风险", text: "虚拟号码诈骗，对方知道你的订单号。你拉黑，仍后怕。", d: { health: -3 }, weight: 5 },
      { id: "E7_08", category: "教育", text: "AI 课卖九块九，内容是让 AI 写「如何赚钱」。", d: { money: -1, edu: 1 }, weight: 5 },
      { id: "E7_09", category: "人情", text: "同学群晒娃录取，你点赞，关掉屏幕发呆。", d: { social: -2, health: -2 }, weight: 6, minAge: 32 },
      { id: "E7_10", category: "健康", text: "体检加项「结节」，复查排期两月。等待像第二种工作。", d: { health: -4, money: -1 }, weight: 7 },
      { id: "E7_11", category: "金钱", text: "消费贷利率上调，你算了一遍，决定先还信用卡。", d: { money: -1, rep: 1 }, weight: 7 },
      { id: "E7_12", category: "职场", text: "Hybrid 办公，周三必须到岗。你通勤两小时，工位空一半。", d: { health: -3, rep: 1 }, weight: 7 },
      { id: "E7_13", category: "机会", text: "出海业务招人，英语要「能开会」。你报了夜课。", d: { edu: 4, money: -1 }, weight: 6 },
      { id: "E7_14", category: "居住", text: "老旧小区加装电梯，低层反对，高层盼。你是中层。", d: { social: -1, health: -1 }, weight: 5, minAge: 35 },
      { id: "E7_15", category: "风险", text: "「稳赚」社群，入群费 299。你观察一周，退了。", d: { rep: 2, money: -1 }, weight: 4 },
      { id: "E7_16", category: "职场", text: "绩效改为季度，浮动加大。你学会存「应急月数」。", d: { rep: 1, edu: 2 }, weight: 7 },
      { id: "E7_17", category: "机会", text: "政府消费券，抢到了。满减规则比高数难。", d: { money: 1 }, weight: 5 },
      { id: "E7_18", category: "教育", text: "孩子兴趣班退费难，合同里「概不退款」加粗。", d: { money: -2, social: -2 }, weight: 6, minAge: 30 },
      { id: "E7_19", category: "健康", text: "健身房跑路，会员群维权。你的年卡剩九个月。", d: { money: -2, health: -2 }, weight: 6 },
      { id: "E7_20", category: "金钱", text: "数字人民币试点，老人问你怎么用。你教了，像教另一种方言。", d: { social: 2, edu: 2 }, weight: 5 }
    ]
  },

  /* ---------- 人生里程碑（一次性，拉长节奏） ---------- */
  milestones: [
    { id: "M012", category: "职场", text: "第一份工作满一年。没人庆祝，你给自己加了蛋。", minMonths: 12, once: true, d: { rep: 3, health: 2 }, weight: 20 },
    { id: "M024", category: "金钱", text: "存款第一次突破五位数千元。你截图，没发朋友圈。", minMonths: 24, once: true, d: { rep: 2, money: 1 }, weight: 20 },
    { id: "M036", category: "居住", text: "搬家第三次，纸箱还是那些。你贴标签：「书·勿丢」。", minMonths: 36, once: true, d: { health: -2, rep: 2 }, weight: 20 },
    { id: "M048", category: "职场", text: "职场第十个年头。体检报告比简历厚。", minMonths: 48, once: true, d: { rep: 3, health: -3 }, weight: 20, minAge: 30 },
    { id: "M060", category: "人情", text: "老同学聚会，半数不聊工作，聊孩子和血压。", minMonths: 60, once: true, d: { social: 3, health: -2 }, weight: 20, minAge: 35 },
    { id: "M072", category: "金钱", text: "房贷还剩一半。你算日期，像算退休。", minMonths: 72, once: true, d: { money: -1, rep: 4 }, weight: 20, minAge: 38 },
    { id: "M096", category: "健康", text: "父母电话变频繁。话题从「钱够吗」到「常回来」。", minMonths: 96, once: true, d: { social: 4, health: -2 }, weight: 20, minAge: 40 },
    { id: "M120", category: "机会", text: "二十年城市生活。你仍能说出第一次来时的出站口。", minMonths: 120, once: true, d: { rep: 5, social: 3 }, weight: 20, minAge: 42 }
  ]
};
