"use strict";

/** 按城市圈层 L1-L5 的专属事件 */
module.exports = {
  L1: [
    { id: "L1_01", category: "居住", text: "握手楼之间晾衣杆碰头，你低头穿过，像走隧道。", d: { health: -1 }, weight: 8 },
    { id: "L1_02", category: "金钱", text: "城中村里通水通电，电费一块二一度。你记表比记工资认真。", d: { money: -1 }, weight: 8 },
    { id: "L1_03", category: "职场", text: "日结工头招工，五十一天。你去了，发现要自带手套。", d: { money: 1, health: -4 }, weight: 7 },
    { id: "L1_04", category: "健康", text: "大排档吃到异物，老板退钱，说「下次请你」。", d: { money: 1, health: -3 }, weight: 6 },
    { id: "L1_05", category: "机会", text: "快递站点招人，「能吃苦」。你干了半月，学会分拣码。", d: { rep: 2, health: -5 }, weight: 6 },
    { id: "L1_06", category: "人情", text: "老乡会凑钱办事，红白喜事都摊。你那份不能少。", d: { money: -1, social: 3 }, weight: 7 },
    { id: "L1_07", category: "风险", text: "黑中介收「介绍费」，工作三天就辞退。你维权，耗不起。", d: { money: -2, rep: -2 }, weight: 5 },
    { id: "L1_08", category: "居住", text: "隔断间隔音差，隔壁打电话你像旁听。", d: { health: -3 }, weight: 8 },
    { id: "L1_09", category: "金钱", text: "二手市场淘风扇，讲价五块。夏天它救你一命。", d: { money: -1, health: 2 }, weight: 6 },
    { id: "L1_10", category: "职场", text: "劳务市场蹲活，太阳晒。工头挑人看身板。", d: { health: -4, rep: 1 }, weight: 7 },
    { id: "L1_11", category: "教育", text: "成人自考广告贴电线杆，「国家承认」。你撕了一张。", d: { edu: 3 }, weight: 5 },
    { id: "L1_12", category: "健康", text: "诊所挂水，没病历。护士手稳，你不知药名。", d: { money: -1, health: 4 }, weight: 6 },
    { id: "L1_13", category: "机会", text: "夜市摆摊卖袜子，一晚卖三双。你算油费，亏的。", d: { money: -1, edu: 2 }, weight: 5 },
    { id: "L1_14", category: "人情", text: "合租室友跑路，房东扣你押金。你冤，合同写连带。", d: { money: -2, social: -2 }, weight: 6 },
    { id: "L1_15", category: "居住", text: "台风天漏水，盆排成一排。你加班回家，床湿一半。", d: { health: -3, money: -1 }, weight: 6 },
    { id: "L1_16", category: "金钱", text: "收废品大爷说纸箱涨价。你攒了一周，够一顿。", d: { money: 1 }, weight: 5 },
    { id: "L1_17", category: "职场", text: "外卖超时罚款，平台扣款比顾客还快。", d: { money: -1, health: -3 }, weight: 7 },
    { id: "L1_18", category: "风险", text: "「无抵押」小广告，电话打过去要「手续费」。", d: { rep: 1 }, weight: 4 },
    { id: "L1_19", category: "健康", text: "公共浴室便宜，搓背大爷说你「劳碌相」。", d: { health: 2, money: -1 }, weight: 5 },
    { id: "L1_20", category: "机会", text: "跟师傅学修车，三个月不给钱。你学会了补胎。", d: { edu: 4, health: -2 }, weight: 5 },
    { id: "L1_21", category: "居住", text: "房东涨租，理由「地铁要通」。地铁图还虚线。", d: { money: -2 }, weight: 7 },
    { id: "L1_22", category: "人情", text: "同乡借住三天，变成三周。你不好意思开口。", d: { social: -2, health: -2 }, weight: 6 },
    { id: "L1_23", category: "职场", text: "工厂两班倒，夜班补贴十块。你拿命换。", d: { money: 1, health: -5 }, weight: 7 },
    { id: "L1_24", category: "金钱", text: "工资发现金，信封厚厚度不准。你数了三遍。", d: { rep: 1 }, weight: 6 },
    { id: "L1_25", category: "教育", text: "免费技能培训，结业证像奖状。你贴墙，激励自己。", d: { edu: 3, rep: 1 }, weight: 5 }
  ],
  L2: [
    { id: "L2_01", category: "职场", text: "地铁早高峰，鞋被踩掉。你单脚跳，仍打卡成功。", d: { health: -2, rep: 1 }, weight: 8 },
    { id: "L2_02", category: "金钱", text: "公积金提取，跑窗口两次。钱到账像年终奖。", d: { money: 2, health: -1 }, weight: 6 },
    { id: "L2_03", category: "居住", text: "合租公约贴 fridge：「谁不洗碗谁洗一个月」。", d: { social: -1, health: -1 }, weight: 7 },
    { id: "L2_04", category: "职场", text: "部门团建自费，AA 制。你去了，照片比饭重要。", d: { money: -1, social: 2 }, weight: 6 },
    { id: "L2_05", category: "健康", text: "带薪病假一天，HR 要医院证明。你硬撑到周末。", d: { health: -3 }, weight: 7 },
    { id: "L2_06", category: "机会", text: "内部转岗机会，要主管签字。你准备了一页纸理由。", d: { rep: 3 }, weight: 6 },
    { id: "L2_07", category: "人情", text: "同事借五百，说下周还。三个月了，你们还说话。", d: { money: -1, social: 1 }, weight: 7 },
    { id: "L2_08", category: "金钱", text: "双十一购物车，清空又满。你只买刚需，仍超支。", d: { money: -2 }, weight: 7 },
    { id: "L2_09", category: "教育", text: "公司报销培训，名额一个。你写了申请，没中。", d: { edu: 1, rep: -1 }, weight: 6 },
    { id: "L2_10", category: "职场", text: "工位换楼层，搬箱子的活自己干。腰响了一声。", d: { health: -3, rep: 1 }, weight: 6 },
    { id: "L2_11", category: "居住", text: "小区门禁换人脸，旧照片不认。你站在门口等保安。", d: { health: -1 }, weight: 5 },
    { id: "L2_12", category: "风险", text: "同事拉你「投资」，年化 15%。你查公司，刚注册。", d: { rep: 2 }, weight: 5 },
    { id: "L2_13", category: "机会", text: "副业接单平台，第一单五星。客户要微信私聊。", d: { money: 1, rep: 2 }, weight: 6 },
    { id: "L2_14", category: "健康", text: "公司体检，你排在最后。空腹到下午两点。", d: { health: -2, rep: 1 }, weight: 6 },
    { id: "L2_15", category: "人情", text: "领导孩子升学宴，礼金标准口头「随意」。你懂。", d: { money: -2, social: 3 }, weight: 6 },
    { id: "L2_16", category: "金钱", text: "物业费纠纷，业主群吵两百条。你关通知。", d: { health: -2 }, weight: 6 },
    { id: "L2_17", category: "职场", text: "OKR 季度复盘，你写了「对齐」。其实只对齐了格式。", d: { rep: 1, health: -2 }, weight: 7 },
    { id: "L2_18", category: "教育", text: "考证报名，机构说「包过」。你选了自学。", d: { edu: 4, money: -1 }, weight: 5 },
    { id: "L2_19", category: "居住", text: "邻居装修违规，物业说「已劝阻」。电钻继续。", d: { health: -4 }, weight: 7 },
    { id: "L2_20", category: "机会", text: "猎头电话，职位比现在高半级。你约了聊，没跳。", d: { rep: 2, social: 1 }, weight: 5 },
    { id: "L2_21", category: "职场", text: "考勤异常解释，你填「地铁故障」。系统要截图。", d: { rep: -1, health: -1 }, weight: 6 },
    { id: "L2_22", category: "金钱", text: "自动续费扣款，忘了关。客服退一半。", d: { money: -1 }, weight: 6 },
    { id: "L2_23", category: "健康", text: "办公室流感，一半人戴口罩。你坚持到岗。", d: { health: -4, rep: 2 }, weight: 6 },
    { id: "L2_24", category: "人情", text: "老乡来出差，你请一顿饭。他回赠家乡腊味。", d: { social: 3, money: -1 }, weight: 5 },
    { id: "L2_25", category: "机会", text: "公司内推奖金，你推荐了朋友。朋友入职，奖金分他一半。", d: { social: 2, rep: 2 }, weight: 5 }
  ],
  L3: [
    { id: "L3_01", category: "职场", text: "带两个新人，绩效算你头上。一个聪明，一个请假。", d: { rep: 2, health: -3 }, weight: 7 },
    { id: "L3_02", category: "机会", text: "行业证书考过，挂靠咨询发来。你拒了，怕风险。", d: { rep: 3, edu: 2 }, weight: 6 },
    { id: "L3_03", category: "金钱", text: "年终奖谈话，「公司困难」。数字仍比上年少一截。", d: { money: -1, rep: -1 }, weight: 7 },
    { id: "L3_04", category: "教育", text: "在职研究生，周末上课。同学是各公司中层。", d: { edu: 5, money: -2, social: 3 }, weight: 6, minAge: 26 },
    { id: "L3_05", category: "人情", text: "客户请吃饭，你控酒。合同仍拖，酒白喝。", d: { social: 2, health: -2 }, weight: 6 },
    { id: "L3_06", category: "居住", text: "换租到次新房，押金两个月。旧房退租扯皮两周。", d: { money: -2, health: -2 }, weight: 7 },
    { id: "L3_07", category: "健康", text: "应酬脂肪肝，医生开运动单。你办健身卡，去三次。", d: { money: -2, health: 3 }, weight: 6 },
    { id: "L3_08", category: "职场", text: "跨部门项目，功劳文档里平分。你知道谁熬夜。", d: { rep: 1, social: -1 }, weight: 7 },
    { id: "L3_09", category: "机会", text: "猎头推 headcount，涨幅 25%。现公司 counter offer。", d: { rep: 3, social: -2 }, weight: 5 },
    { id: "L3_10", category: "金钱", text: "基金定投三年，收益不如余额宝。你仍坚持。", d: { money: 1, edu: 2 }, weight: 6 },
    { id: "L3_11", category: "风险", text: "帮客户「走账」，财务提醒合规。你断了联系。", d: { rep: 2, social: -3 }, weight: 4 },
    { id: "L3_12", category: "教育", text: "孩子择校，积分不够。你研究政策像研究 KPI。", d: { edu: 3, health: -3 }, weight: 6, minAge: 30 },
    { id: "L3_13", category: "职场", text: "晋升答辩，PPT 改七版。Questions 你背了，仍紧张。", d: { rep: 4, health: -3 }, weight: 6 },
    { id: "L3_14", category: "人情", text: "借车给同事，刮蹭。保险走他的，你耗时间。", d: { social: -1, health: -2 }, weight: 5 },
    { id: "L3_15", category: "居住", text: "买房摇号，第六次没中。你继续交社保。", d: { health: -3, rep: 1 }, weight: 6, minAge: 28 },
    { id: "L3_16", category: "机会", text: "副业咨询第一单，客户要发票。你研究个体户。", d: { money: 2, edu: 3 }, weight: 5 },
    { id: "L3_17", category: "金钱", text: "装修超预算，「加点钱效果更好」。你加了三次。", d: { money: -3 }, weight: 6, minAge: 28 },
    { id: "L3_18", category: "健康", text: "睡眠监测 App 说你「深睡不足」。你删 App，睡稍好。", d: { health: 2 }, weight: 5 },
    { id: "L3_19", category: "职场", text: "360 评估，匿名评语尖。你知道是谁，不说。", d: { rep: -2, health: -2 }, weight: 6 },
    { id: "L3_20", category: "机会", text: "校友内推，面试官是同级。聊得不错，等 HC。", d: { social: 3, rep: 2 }, weight: 5 },
    { id: "L3_21", category: "人情", text: "随礼 2000，你咬牙。对方回礼时你已升职。", d: { money: -2, social: 2 }, weight: 6 },
    { id: "L3_22", category: "教育", text: "英语面试，口语卡壳。你报外教，钱包瘦。", d: { edu: 4, money: -2 }, weight: 5 },
    { id: "L3_23", category: "职场", text: "出差补贴砍半，「行业下行」。你仍飞。", d: { money: -1, health: -3 }, weight: 7 },
    { id: "L3_24", category: "金钱", text: "信用卡积分换里程，算不清。最后换锅。", d: { money: 1 }, weight: 4 },
    { id: "L3_25", category: "健康", text: "甲状腺结节随访，医生说「观察」。你观察自己。", d: { health: -2, edu: 2 }, weight: 6 }
  ],
  L4: [
    { id: "L4_01", category: "金钱", text: "私人银行理财，门槛五十万。你刚好够，心跳快。", d: { money: -2, rep: 3 }, weight: 6 },
    { id: "L4_02", category: "职场", text: "董事会材料，你熬夜核对。错一个小数，被点名。", d: { rep: -2, health: -4 }, weight: 6 },
    { id: "L4_03", category: "机会", text: "LP 晚宴，听不懂一半笑话。你笑，像练习。", d: { social: 2, edu: 2 }, weight: 5 },
    { id: "L4_04", category: "人情", text: "孩子国际学校开放日，家长比孩子紧张。", d: { money: -2, social: 3 }, weight: 5, minAge: 32 },
    { id: "L4_05", category: "居住", text: "江景房视野，雾霾天看不见江。你仍付景观溢价。", d: { money: -1 }, weight: 5, minAge: 35 },
    { id: "L4_06", category: "风险", text: "担保签字，律师朋友说别签。你签了，信关系。", d: { rep: -4, money: -2 }, weight: 4 },
    { id: "L4_07", category: "教育", text: "EMBA 同学名片，title 比公司官网长。", d: { social: 4, money: -2 }, weight: 5, minAge: 32 },
    { id: "L4_08", category: "职场", text: "期权解禁，税比想象高。你卖一半，留一半。", d: { money: 3, edu: 2 }, weight: 5 },
    { id: "L4_09", category: "健康", text: "私家医生加微信，随时问。你不敢多发。", d: { money: -1, health: 4 }, weight: 5 },
    { id: "L4_10", category: "机会", text: "天使投资朋友项目，占股 2%。条款书厚得像字典。", d: { money: -2, rep: 3 }, weight: 4 },
    { id: "L4_11", category: "金钱", text: "家族信托宣传册，门槛八位数。你收起来。", d: { edu: 3 }, weight: 4, minAge: 38 },
    { id: "L4_12", category: "人情", text: "饭局座位有主位，你学会等指示。", d: { social: 3, rep: 1 }, weight: 6 },
    { id: "L4_13", category: "职场", text: "媒体采访，稿经 PR 改三遍。你像念稿。", d: { rep: 4, health: -2 }, weight: 5 },
    { id: "L4_14", category: "居住", text: "第二套房空置，交着物业费。租售比算不过。", d: { money: -2 }, weight: 5, minAge: 35 },
    { id: "L4_15", category: "风险", text: "内幕消息电话，你挂断。仍被调查问话。", d: { rep: -3, health: -4 }, weight: 3 },
    { id: "L4_16", category: "机会", text: "拍卖会上举了一次牌，价格飞。你放下，看戏。", d: { social: 2, edu: 2 }, weight: 4 },
    { id: "L4_17", category: "教育", text: "孩子留学顾问，套餐三十万。你比较了五家。", d: { money: -3, edu: 2 }, weight: 4, minAge: 35 },
    { id: "L4_18", category: "健康", text: "高尔夫应酬，杆数不重要。谈成了，腰闪了。", d: { social: 3, health: -3 }, weight: 5 },
    { id: "L4_19", category: "职场", text: "行业峰会演讲，台下拍照。你讲「长期主义」。", d: { rep: 5, health: -2 }, weight: 5 },
    { id: "L4_20", category: "金钱", text: "境外账户合规申报，表格像迷宫。", d: { edu: 3, health: -2 }, weight: 4 },
    { id: "L4_21", category: "人情", text: "慈善晚宴，露名捐资。你计算 PR 值。", d: { money: -2, rep: 4 }, weight: 5 },
    { id: "L4_22", category: "机会", text: "被邀独立董事，津贴诱人。你查公司法。", d: { rep: 4, edu: 3 }, weight: 4, minAge: 40 },
    { id: "L4_23", category: "居住", text: "老房翻新，设计师说「要品味」。账单也要。", d: { money: -3, rep: 2 }, weight: 5 },
    { id: "L4_24", category: "职场", text: "接班讨论，没有你。你微笑，记笔记。", d: { rep: -2, edu: 3 }, weight: 5, minAge: 38 },
    { id: "L4_25", category: "健康", text: "体检发现斑块，私立医院复查。心稳些，钱包薄些。", d: { money: -2, health: 3 }, weight: 5, minAge: 40 }
  ],
  L5: [
    { id: "L5_01", category: "风险", text: "地下钱庄利息按天，借条手写。你看见，没借。", d: { rep: -2, health: -2 }, weight: 5 },
    { id: "L5_02", category: "风险", text: "刷单返现，先垫钱。朋友被骗五万，你借钱给他。", d: { money: -2, social: 2 }, weight: 4 },
    { id: "L5_03", category: "机会", text: "灰色渠道办证件，快但贵。你选正规，慢。", d: { rep: 2, money: -1 }, weight: 4 },
    { id: "L5_04", category: "金钱", text: "高利贷催收电话，打给紧急联系人。你换号。", d: { health: -4, rep: -3 }, weight: 4 },
    { id: "L5_05", category: "人情", text: "夜场熟人介绍「资源」，你明白意思，告辞。", d: { social: -2, rep: 1 }, weight: 5 },
    { id: "L5_06", category: "职场", text: "黑工无合同，工伤自负。你劝人走，人不听。", d: { social: -1, health: -2 }, weight: 5 },
    { id: "L5_07", category: "风险", text: "赌球群，有人晒单。你退群，仍有人私聊。", d: { health: -2 }, weight: 4 },
    { id: "L5_08", category: "机会", text: "废品站旁边「收号」，你知道是诈骗链条一环。", d: { rep: 1 }, weight: 3 },
    { id: "L5_09", category: "健康", text: "廉价诊所输液，针头复用传闻。你换正规医院。", d: { money: -1, health: 3 }, weight: 5 },
    { id: "L5_10", category: "金钱", text: "「套现」广告，POS 机。你想起信用卡条款。", d: { rep: -1 }, weight: 4 },
    { id: "L5_11", category: "风险", text: "帮运「货」，报酬高。你在路口转身走了。", d: { rep: 2, health: 1 }, weight: 4 },
    { id: "L5_12", category: "人情", text: "黑中介要「喝茶费」，你报警，事小化了。", d: { social: -1, rep: 2 }, weight: 4 },
    { id: "L5_13", category: "职场", text: "无照经营被查，摊主跑你帮忙看摊。你看了十分钟。", d: { social: 1, rep: -1 }, weight: 4 },
    { id: "L5_14", category: "机会", text: "「内部渠道」办贷款，先交保证金。你没交。", d: { rep: 2 }, weight: 4 },
    { id: "L5_15", category: "健康", text: "熬夜后巷吃野摊，第二天肠胃抗议。便宜有价。", d: { health: -4, money: 1 }, weight: 5 },
    { id: "L5_16", category: "金钱", text: "当铺估价，旧表不如想象。你赎回，当纪念。", d: { money: -1 }, weight: 4 },
    { id: "L5_17", category: "风险", text: "线上博彩链接，弹窗关不掉。你重装系统。", d: { health: -2, edu: 1 }, weight: 3 },
    { id: "L5_18", category: "人情", text: "熟人求「洗流水」，你删好友。旧情在风险前薄。", d: { social: -3, rep: 2 }, weight: 4 },
    { id: "L5_19", category: "职场", text: "日结黑工地，安全帽没绳。你系了，别人笑。", d: { health: -3, rep: 1 }, weight: 5 },
    { id: "L5_20", category: "机会", text: "废旧厂房「低租创业」，合同一月一签。你拍了照，没租。", d: { edu: 2 }, weight: 4 }
  ]
};
